# Generated by Django 3.2.4 on 2021-06-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scraper_lastkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='insta',
            field=models.CharField(max_length=50, null=True, verbose_name='Instagram accaunt'),
        ),
    ]
