# Generated by Django 3.2.4 on 2021-06-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scraper_insta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50, verbose_name='Channel id')),
                ('is_active', models.BooleanField(default=True)),
                ('lastkey', models.CharField(max_length=50, null=True, verbose_name='Last key')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta', models.CharField(max_length=50, null=True, verbose_name='Instagram accaunt')),
            ],
        ),
        migrations.DeleteModel(
            name='Scraper',
        ),
    ]
