# Generated by Django 3.2.4 on 2021-06-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20210617_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='lastkey',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(default=0, max_length=50, verbose_name='Channel id'),
        ),
        migrations.AddField(
            model_name='channel',
            name='lastkey_insta',
            field=models.CharField(default=0, max_length=50, verbose_name='Last key'),
        ),
        migrations.AddField(
            model_name='profile',
            name='channel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scraper.channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='insta',
            field=models.CharField(default=0, max_length=50, verbose_name='Instagram accaunt'),
        ),
    ]
