# Generated by Django 3.2.4 on 2021-06-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20210617_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastkey', models.CharField(default=0, max_length=50, verbose_name='Last key')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.profile')),
            ],
        ),
    ]
