# Generated by Django 3.2.4 on 2021-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_lastkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastkey_insta',
            field=models.CharField(default=0, max_length=50, verbose_name='Last key'),
        ),
        migrations.DeleteModel(
            name='LastKey',
        ),
    ]
