# Generated by Django 3.2.4 on 2021-08-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20210618_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='lastkey_insta',
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastkey_insta',
            field=models.CharField(default=None, max_length=50, verbose_name='Last key'),
        ),
    ]
